version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Adjust this if your backend runs on a different port internally
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Mapping port 80 of Nginx to port 80 of the host machine
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always

volumes:
  mongo-data: {}

networks:
  app-network:
    driver: bridge
